# Generated by Django 5.0.6 on 2024-10-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SDGoals',
            fields=[
                ('sdgId', models.AutoField(primary_key=True, serialize=False)),
                ('sdgName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
        ),
    ]
