# Generated by Django 5.0.6 on 2024-10-02 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdgDashApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sdgoals',
            table='man_sdg',
        ),
    ]
