# Generated by Django 5.0.6 on 2024-10-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdgDashApp', '0002_alter_sdgoals_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDGIndicator',
            fields=[
                ('indId', models.AutoField(primary_key=True, serialize=False)),
                ('indCode', models.CharField(max_length=50)),
                ('indDesc', models.CharField(max_length=500)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'man_sdg_indicator',
            },
        ),
        migrations.CreateModel(
            name='SDGTarget',
            fields=[
                ('targetId', models.AutoField(primary_key=True, serialize=False)),
                ('targetCode', models.CharField(max_length=50)),
                ('targetDesc', models.CharField(max_length=500)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'man_sdg_target',
            },
        ),
    ]
