# Generated by Django 5.0.6 on 2024-10-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdgDashApp', '0004_sdgindicator_targetid_sdgtarget_sdgid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdgindicator',
            name='indDesc',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='sdgoals',
            name='description',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='sdgtarget',
            name='targetDesc',
            field=models.CharField(max_length=800),
        ),
    ]
