# Generated by Django 5.0.6 on 2024-10-17 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdgDashApp', '0006_sdgscorecard_sdgscorecarddet_sustainstrat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uigreenmetric',
            old_name='greeName',
            new_name='greenName',
        ),
    ]
