# Generated by Django 5.0.6 on 2024-10-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdgDashApp', '0007_rename_greename_uigreenmetric_greenname'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdgscorecard',
            name='enCodedBy',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sdgscorecard',
            name='enCodedDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sdgscorecard',
            name='sdgImpYear',
            field=models.IntegerField(),
        ),
    ]
