# Generated by Django 5.0.6 on 2024-10-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdgDashApp', '0008_sdgscorecard_encodedby_sdgscorecard_encodeddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdgscorecarddet',
            name='isActive',
            field=models.CharField(default='Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='sdgscorecarddet',
            name='indId',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='sdgscorecarddet',
            name='sdgId',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sdgscorecarddet',
            name='targetId',
            field=models.CharField(max_length=100),
        ),
    ]
