# Generated by Django 5.0.6 on 2024-12-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdgDashApp', '0011_sdgpolicies'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdgpolicies',
            name='linkPath',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vegetationmap',
            name='linkPath',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sdgpolicies',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='sdgpolicies',
            name='imgPath',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
