# Generated by Django 5.0.6 on 2024-12-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdgDashApp', '0012_sdgpolicies_linkpath_vegetationmap_linkpath_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdgpolicies',
            name='linkPath',
            field=models.ImageField(blank=True, default='def-article-img.jpg', upload_to=''),
        ),
    ]
