# Generated by Django 5.0.6 on 2024-12-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdgDashApp', '0013_alter_sdgpolicies_linkpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdgpolicies',
            name='imgPath',
            field=models.ImageField(blank=True, default='def-article-img.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='sdgpolicies',
            name='linkPath',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
