# Generated by Django 5.0.6 on 2025-01-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdgDashApp', '0014_alter_sdgpolicies_imgpath_alter_sdgpolicies_linkpath'),
    ]

    operations = [
        migrations.CreateModel(
            name='sdgNews',
            fields=[
                ('newsId', models.AutoField(primary_key=True, serialize=False)),
                ('sdgId', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=850)),
                ('excerpt', models.CharField(max_length=230)),
                ('datePublished', models.DateField(blank=True, null=True)),
                ('author', models.CharField(max_length=100)),
                ('imgPath', models.ImageField(blank=True, upload_to='')),
                ('linkPath', models.CharField(max_length=500, null=True)),
                ('createdDate', models.DateField(blank=True, null=True)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'man_sdg_news',
            },
        ),
    ]
